FROM python:3.6-buster
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /home/ubuntu/new
COPY . /home/ubuntu/new
WORKDIR /home/ubuntu/new
RUN pip install --upgrade pip
RUN apt-get install -y default-libmysqlclient-dev
RUN pip install -r requirements.txt
RUN chmod u+x test_script.sh
ENTRYPOINT [ "./test_script.sh" ]
